"""Add external_id to FutureMediaGoal

Revision ID: 6b574e17929b
Revises: d6910e02b08d
Create Date: 2026-08-19 15:59:11.727117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b574e17929b'
down_revision = 'd6910e02b08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_media_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_media_goal', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
