"""Add poster_path and release_year to FutureMediaGoal

Revision ID: 7ba2ae3915b3
Revises: 6b574e17929b
Create Date: 2026-08-19 16:11:45.550856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba2ae3915b3'
down_revision = '6b574e17929b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_media_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_media_goal', schema=None) as batch_op:
        batch_op.drop_column('release_year')
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###
