"""Add backlog item model

Revision ID: d6910e02b08d
Revises: 9cbcd953e351
Create Date: 2026-08-19 15:47:18.234829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6910e02b08d'
down_revision = '9cbcd953e351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('game_platform', sa.String(length=100), nullable=True),
    sa.Column('book_format', sa.String(length=100), nullable=True),
    sa.Column('book_source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backlog_item')
    # ### end Alembic commands ###
