"""Initial migration

Revision ID: d906bd0a2b72
Revises: 
Create Date: 2026-05-25 14:56:28.451686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd906bd0a2b72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('franchises')
    op.drop_table('orders')
    op.drop_table('painting_statuses')
    op.drop_table('products')
    op.drop_table('named_events')
    op.drop_table('painting_event')
    op.drop_table('users')
    op.drop_table('paintings')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('applied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('table_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('travel_expense', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('named_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['named_event_id'], ['named_events.id'], name=op.f('events_named_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_table('paintings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('franchise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_original_design', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canvas_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canvas_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_colors_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('list_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_of_materials', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('painting_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('paintings_franchise_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('paintings_order_id_fkey')),
    sa.ForeignKeyConstraint(['painting_status_id'], ['painting_statuses.id'], name=op.f('paintings_painting_status_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('paintings_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paintings_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('paintings_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('painting_event',
    sa.Column('painting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sold_at_event', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sold_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sold_to_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('painting_event_event_id_fkey')),
    sa.ForeignKeyConstraint(['painting_id'], ['paintings.id'], name=op.f('painting_event_painting_id_fkey')),
    sa.PrimaryKeyConstraint('painting_id', 'event_id', name=op.f('painting_event_pkey'))
    )
    op.create_table('named_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('first_appearance_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('named_events_pkey')),
    sa.UniqueConstraint('name', name=op.f('named_events_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey')),
    sa.UniqueConstraint('name', name=op.f('products_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('painting_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('painting_statuses_pkey')),
    sa.UniqueConstraint('name', name=op.f('painting_statuses_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('mailing_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agreed_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('painting_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('orders_event_id_fkey')),
    sa.ForeignKeyConstraint(['painting_id'], ['paintings.id'], name=op.f('orders_painting_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey')),
    sa.UniqueConstraint('painting_id', name=op.f('orders_painting_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('franchises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('franchises_pkey')),
    sa.UniqueConstraint('name', name=op.f('franchises_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
